const BASE_URL = "https://rd3.clubly.io/";
export const tempToken =
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTgzMTQ3NDcxLCJqdGkiOiIwMDIzMTQ1YTAwYzg0ZmJlYTU1MTliOWQ1YTk3MmExMyIsInVzZXJfaWQiOjI2fQ.71qqT0gXmTprO0WYbO2H28AR9lHI23Izz8461m6hAPU";
export const APPLICATIONS_URL = BASE_URL + "property-application/application";
export const PROPERTIES_URL = BASE_URL + "unit-property/property";
export const UNITS_URL = BASE_URL + "unit-property/unit";
export const BRANCH_URL = BASE_URL + "user/branch";
export const USER_PROFILE = BASE_URL + "user/list";
export const USER_EMPLOYMENT = BASE_URL + "user/employment-info";
export const USER_IMMIGRATION = BASE_URL + "user/immigration-info";
export const USER_RESIDENCE = BASE_URL + "user/residence-info";
export const UNIT_TYPES_ROUTE = BASE_URL + "unit-property/unit-type";
export const DOCUMENTS_LOOK_UP_URL = BASE_URL + "misc/documents-lookup";
export const FACILITY_LOOK_UP_URL = BASE_URL + "misc/facility";
export const CHARGES_LOOK_UP_URL = BASE_URL + "misc/charges-lookup";
export const UNIT_TYPE_LOOK_UP = BASE_URL + "unit-property/unit-type";
export const PROPERTY_CONTROLLER_URL = PROPERTIES_URL;
export const UNIT_CONTROLLER_URL = UNITS_URL;
export const UNIT_TERM_URL = BASE_URL + "unit-property/unit-term";
export const UNIT_FACILITY_URL = BASE_URL + "unit-property/unit-facility";
export const UNIT_IMAGE_URL = BASE_URL + "unit-property/unit-image";
export const UNIT_COMMISSION_URL = BASE_URL + "unit-property/unit-commission";
export const GENERIC_FEE_URL = BASE_URL + "misc/fee";
export const FILE_UPLOAD_URL = BASE_URL + "misc/file-upload";
export const TEAMS_URL = BASE_URL + "user/team";
export const TEAM_REQUEST_URL =
  BASE_URL + "user/join-agency-request?request_status=pending";
export const PROPERTY_URL = PROPERTY_CONTROLLER_URL;
