const BASE_URL = "https://rd3.rentright.co/";
export const PUBLIC_URL = "https://rfrontend.clubly.io/";
export const tempToken =
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTgzMTQ3NDcxLCJqdGkiOiIwMDIzMTQ1YTAwYzg0ZmJlYTU1MTliOWQ1YTk3MmExMyIsInVzZXJfaWQiOjI2fQ.71qqT0gXmTprO0WYbO2H28AR9lHI23Izz8461m6hAPU";
export const APPLICATIONS_URL = BASE_URL + "property-application/application";
export const PROPERTIES_URL = BASE_URL + "unit-property/property";
export const LEASE_URL = BASE_URL + "property-lease/leases";
export const LEASE_TEMPLATE_URL = BASE_URL + "property-lease/templates";
export const LEASE_GENERATE_URL = BASE_URL + "property-lease/lease-interface";
export const LEASE_SIGNATURE_URL = BASE_URL + "property-lease/signatures";
export const LEASE_CHARGE_URL = BASE_URL + "property-lease/lease-charge";
export const LEASE_DECLARATION_URL =
  BASE_URL + "property-lease/lease-declaration";
export const UNITS_URL = BASE_URL + "unit-property/unit";
export const BRANCH_URL = BASE_URL + "user/branch";
export const USER_PROFILE = BASE_URL + "user/list";
export const USER_BASIC = BASE_URL + "user/basic-info";
export const USER_ROLE = BASE_URL + "user/roles";
export const SWITCH_ROLE = BASE_URL + "user/switch-role";
export const USER_PROFILE_MAIN = BASE_URL + "user/profile";
export const USER_EMPLOYMENT = BASE_URL + "user/employment-info";
export const USER_IMMIGRATION = BASE_URL + "user/immigration-info";
export const USER_RESIDENCE = BASE_URL + "user/resident-info";
export const UNIT_TYPES_ROUTE = BASE_URL + "unit-property/unit-type";
export const DOCUMENTS_LOOK_UP_URL = BASE_URL + "misc/documents-lookup";
export const FACILITY_LOOK_UP_URL = BASE_URL + "misc/facility";
export const CHARGES_LOOK_UP_URL = BASE_URL + "misc/charges-lookup";
export const UNIT_TYPE_LOOK_UP = BASE_URL + "unit-property/unit-type";
export const PROPERTY_CONTROLLER_URL = PROPERTIES_URL;
export const UNIT_CONTROLLER_URL = UNITS_URL;
export const UNIT_TERM_URL = BASE_URL + "unit-property/unit-term";
export const UNIT_FACILITY_URL = BASE_URL + "unit-property/unit-facility";
export const UNIT_IMAGE_URL = BASE_URL + "unit-property/unit-image";
export const UNIT_COMMISSION_URL = BASE_URL + "unit-property/unit-commission";
export const GENERIC_FEE_URL = BASE_URL + "misc/fee";
export const FILE_UPLOAD_URL = BASE_URL + "misc/file-upload";
export const MISC_TEMPLATE_URL = BASE_URL + "misc/templates";
export const TEAMS_URL = BASE_URL + "user/team";
export const TEAM_REQUEST_URL =
  BASE_URL + "user/join-agency-request?request_status=pending";
export const PROPERTY_URL = PROPERTY_CONTROLLER_URL;
export const USER_ME = BASE_URL + "user/me";
export const GET_ACCESS_TOKEN = BASE_URL + "gateway/refresh";
export const LOGOUT = BASE_URL + "gateway/logout";
export const DASHBOARD_URL = BASE_URL + "user/dashboard";
export const AGENCY_TRANSACTION_URL = BASE_URL + "payment/agency_transactions";
export const GENERATE_INVOICE_URL = BASE_URL + "payment/generate/";
export const INITIATE_INVOICE_TRANSACTION_URL =
  BASE_URL + "payment/invoice-transaction-initiation/";
export const VERIFY_INVOICE_TRANSACTION_URL =
  BASE_URL + "payment/invoice-transaction-verification/";
